### ISSUE TITLE
Importation impossible 

### ISSUE THREAD

**Issue by MangoMango666** [igeofr/qgis2#11]
Bonjour.

J'ai systématiquement une erreur lorsque je charge les fichiers : "Parse error at line 43, column 91:
unexpected character".
C'est la même erreur pour tous les fichiers (avec les mêmes numéros de ligne et colonne).

Je suis sous QGIS 2.18 sous Linux Mint 18.

**Comment by igeofr** [comment]
Bonjour,
Comment vous chargez le fichier dans QGIS ?

Pour ajouter des flux dans QGIS depuis un fichier xml :

1. Menu "Couche" / Ajouter une couche / Ajouter une couche WMS ou WFS
2. Cliquer sur charger et sélectionner le xml
3. Sélectionner les flux à importer
4. Importer

**Comment by MangoMango666** [comment]
Bonjour.
Je n'ai plus de problème ! Merci.
