### ISSUE TITLE
Structurer le dépôt pour Qgis Ressources sharing

### ISSUE THREAD

**Issue by Bobolica** [igeofr/qgis2#8]
Salut, 
Que penses tu de structurer le dépôt pour en faire un compatible avec le plugin Qgis ressources sharing ?

http://www.akbargumbira.com/qgis_resources_sharing/

En gros après une lecture rapide, il s'agirait de modifier la manière dont sont organisés les différents fichiers et dossier et ensuite mettre un fichier de métadonnées 

Modèle de métadonnées
http://www.akbargumbira.com/qgis_resources_sharing/author/creating-metadata.html
Structure des fichiers 
http://www.akbargumbira.com/qgis_resources_sharing/author/repository-structure.html

Si tu penses que c'est une bonne idée, je veux bien jouer un peu pour le faire.
A+

**Comment by igeofr** [comment]
Salut Bobo, 
J'ai déjà créé un dépôt compatible mais je n'ai pas mis à jour celui-ci! 

Le dépôt se trouve ici : https://github.com/igeofr/qgis_styles

Bilan : il faut que je mette à jour tout ça:)

Flo

**Comment by igeofr** [comment]
Re,
Normalement, le dépôt est maintenant à jour.

Flo

**Comment by Bobolica** [comment]
Yo, 
cool, merci //
